/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppHome {
    'activeSong': any;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'activeSong'?: any;
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppProfile {
    'match': MatchResults;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'match'?: MatchResults;
  }

  interface AppRoot {
    'activeSong': any;
  }
  interface AppRootAttributes extends StencilHTMLAttributes {
    'activeSong'?: any;
  }

  interface BvaSongdrawer {
    'song': string;
  }
  interface BvaSongdrawerAttributes extends StencilHTMLAttributes {
    'onCloseDrawer'?: (event: CustomEvent) => void;
    'song'?: string;
  }

  interface BvaWheel {}
  interface BvaWheelAttributes extends StencilHTMLAttributes {
    'onOpenSong'?: (event: CustomEvent) => void;
  }
}

declare global {
  interface StencilElementInterfaces {
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRoot': Components.AppRoot;
    'BvaSongdrawer': Components.BvaSongdrawer;
    'BvaWheel': Components.BvaWheel;
  }

  interface StencilIntrinsicElements {
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-root': Components.AppRootAttributes;
    'bva-songdrawer': Components.BvaSongdrawerAttributes;
    'bva-wheel': Components.BvaWheelAttributes;
  }


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLBvaSongdrawerElement extends Components.BvaSongdrawer, HTMLStencilElement {}
  var HTMLBvaSongdrawerElement: {
    prototype: HTMLBvaSongdrawerElement;
    new (): HTMLBvaSongdrawerElement;
  };

  interface HTMLBvaWheelElement extends Components.BvaWheel, HTMLStencilElement {}
  var HTMLBvaWheelElement: {
    prototype: HTMLBvaWheelElement;
    new (): HTMLBvaWheelElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-root': HTMLAppRootElement
    'bva-songdrawer': HTMLBvaSongdrawerElement
    'bva-wheel': HTMLBvaWheelElement
  }

  interface ElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'bva-songdrawer': HTMLBvaSongdrawerElement;
    'bva-wheel': HTMLBvaWheelElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
